package view;

/**
 * This list of enums represents the list of views that the view can show. This list is
 * provided to the controller.
 */
public enum TypeofViews {
  MAIN,
  CREATE_PORTFOLIO_NAME_SCREEN,
  CREATE_PORTFOLIO,
  BUY_STOCKS_MAIN,
  LIST_OF_STOCKS,
  SHOW_STOCK_DATA,
  BUY_STOCKS_VALUE,
  BUY_ANOTHER_STOCK,
  DISPLAY_PORTFOLIO_CREATED,
  PORTFOLIO_COMPOSITION,
  PORTFOLIO_INDIVIDUAL_LIST,
  PORTFOLIO_NAME_REENTER,
  STOCK_BUY_REENTER,
  BUY_STOCKS_INVALID_RETRY,
  GOBACK_MAINMENU_OPTION,
  PORTFOLIO_INDIVIDUAL_LIST_WITH_DATE,
  NOT_VALID_INPUT_SCREEN,
  NO_PORTFOLIO,
  PORTFOLIO_INVALID_ENTRY,
  PORTFOLIO_ALREADY_EXISTS,
  PF_REENTER_DUPLICATE_NAME,
  WHICH_PORTFOLIO_CHECK, LIST_OF_STOCKS_ON_DATE, CHOOSE_LIST_OF_STOCKS_ON_DATE, PORTFOLIO_PERFORMANCE, NOT_VALID_MAIN_MENU, PORTFOLIO_PERFORMANCE_DATE_INPUT, DATE_RENTER
}
