package view;

public enum TypeofViews {
  MAIN,
  CREATE_PORTFOLIO_NAME_SCREEN,
  CREATE_PORTFOLIO,
  BUY_STOCKS_MAIN,
  LIST_OF_STOCKS,
  SHOW_STOCK_DATA,
  BUY_STOCKS_VALUE,
  BUY_ANOTHER_STOCK;
}
