package view;

public enum TypeofViews {
  MAIN,
  CREATE_PORTFOLIO_NAME_SCREEN,
  CREATE_PORTFOLIO,
  BUY_STOCKS_MAIN,
  LIST_OF_STOCKS,
  SHOW_STOCK_DATA,
  BUY_STOCKS_VALUE,
  BUY_ANOTHER_STOCK,
  DISPLAY_PORTFOLIO_CREATED,
  PORTFOLIO_COMPOSITION,
  PORTFOLIO_INDIVIDUAL_LIST,
  PORTFOLIO_NAME_REENTER,
  STOCK_BUY_REENTER,
  BUY_STOCKS_INVALID_RETRY,
  REVIEW_STOCK;
}
